import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/dbConnect';
import FAQCategory, { IFAQCategory } from '@/models/FAQCategory';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import rateLimit from '@/lib/rateLimit';

const limiter = rateLimit({
  interval: 60 * 1000, // 1 minute
  uniqueTokenPerInterval: 500, // Max 500 unique IPs
});

export async function POST(req: NextRequest) {
  // Get IP from headers instead of req.ip
  const forwardedFor = req.headers.get('x-forwarded-for');
  const ip = forwardedFor ? forwardedFor.split(',')[0] : '127.0.0.1';
  const limitPerIp = 10; // Max 10 category creations per IP per minute for this route
  
  try {
    const isRateLimited = limiter.check(req, limitPerIp, ip);
    // Remove tokenCache access since it's not exposed in the type
    const rateLimitHeaders = limiter.getHeaders(limitPerIp, 0, Math.ceil(Date.now() / 1000) + 60);

    if (isRateLimited) {
      return NextResponse.json({ message: 'Too many requests. Please try again later.' }, { status: 429, headers: rateLimitHeaders });
    }

    const session = await getServerSession(authOptions);
    if (!session || session.user?.role !== 'admin') {
      return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
    }

    await dbConnect();

    const body = await req.json();
    const { name, description, slug } = body;

    if (!name) {
      return NextResponse.json({ message: 'Category name is required.' }, { status: 400 });
    }

    // Slug can be auto-generated by the model if not provided
    const newCategoryData: Partial<IFAQCategory> = { name, description };
    if (slug) {
      newCategoryData.slug = slug;
    }

    const newCategory = new FAQCategory(newCategoryData);
    await newCategory.save();

    return NextResponse.json(newCategory, { status: 201, headers: rateLimitHeaders });
  } catch (error: any) {
    console.error('Error creating FAQ category:', error);
    if (error.code === 11000) { // Duplicate key error
      return NextResponse.json({ message: 'A category with this name or slug already exists.' }, { status: 409 });
    }
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user?.role !== 'admin') {
      return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
    }

    await dbConnect();

    const categories = await FAQCategory.find({}).sort({ name: 1 }); // Sort by name
    return NextResponse.json(categories, { status: 200 });
  } catch (error: any) {
    console.error('Error fetching FAQ categories:', error);
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}