import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/dbConnect';
import FAQEntry, { IFAQEntry } from '@/models/FAQEntry';
import FAQCategory from '@/models/FAQCategory'; // To validate category existence
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import mongoose from 'mongoose';

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || session.user?.role !== 'admin') {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  try {
    const body = await req.json();
    const { question, answer, category: categoryId, isPublished, slug } = body;

    if (!question || !answer || !categoryId) {
      return NextResponse.json({ message: 'Question, answer, and category ID are required.' }, { status: 400 });
    }

    if (!mongoose.Types.ObjectId.isValid(categoryId)) {
        return NextResponse.json({ message: 'Invalid category ID format.' }, { status: 400 });
    }

    const categoryExists = await FAQCategory.findById(categoryId);
    if (!categoryExists) {
        return NextResponse.json({ message: 'Referenced FAQ Category not found.' }, { status: 404 });
    }

    const newEntryData: Partial<IFAQEntry> = {
        question,
        answer,
        category: new mongoose.Types.ObjectId(categoryId),
        isPublished: isPublished !== undefined ? isPublished : false, // Default to false if not provided
    };

    if (slug) {
        newEntryData.slug = slug;
    }
    // Slug will be auto-generated by the model if not provided and question is present

    const newEntry = new FAQEntry(newEntryData);
    await newEntry.save();

    return NextResponse.json(newEntry, { status: 201 });
  } catch (error: any) {
    console.error('Error creating FAQ entry:', error);
    if (error.code === 11000) { // Duplicate key error (likely for slug)
      return NextResponse.json({ message: 'An FAQ entry with this slug already exists.' }, { status: 409 });
    }
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || session.user?.role !== 'admin') {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  try {
    // For admin, list all entries, potentially populate category for display
    const entries = await FAQEntry.find({})
      .populate<{ category: mongoose.Document & { name: string, slug: string } }>({
        path: 'category',
        select: 'name slug _id' // Select specific fields from category
      })
      .sort({ createdAt: -1 }); // Sort by newest first

    return NextResponse.json(entries, { status: 200 });
  } catch (error: any) {
    console.error('Error fetching FAQ entries:', error);
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}