import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/dbConnect';
import BlogPost, { IBlogPost } from '@/models/BlogPost';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route'; // Assuming this is the correct path
import mongoose from 'mongoose';

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || session.user?.role !== 'admin') {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  try {
    const body = await req.json();
    const { title, content, isPublished, slug } = body;

    if (!title || !content) {
      return NextResponse.json({ message: 'Title and content are required.' }, { status: 400 });
    }

    const authorId = session.user.id; // Get author ID from the session

    const newPostData: Partial<IBlogPost> = {
      title,
      content,
      author: new mongoose.Types.ObjectId(authorId),
      isPublished: isPublished !== undefined ? isPublished : false,
    };

    if (slug) {
      newPostData.slug = slug;
    }
    // Slug will be auto-generated by the model if not provided and title is present

    const newPost = new BlogPost(newPostData);
    await newPost.save();

    return NextResponse.json(newPost, { status: 201 });
  } catch (error: any) {
    console.error('Error creating blog post:', error);
    if (error.code === 11000) { // Duplicate key error (likely for slug)
      return NextResponse.json({ message: 'A blog post with this slug already exists.' }, { status: 409 });
    }
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || session.user?.role !== 'admin') {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  try {
    // For admin, list all posts, populate author for display
    const posts = await BlogPost.find({})
      .populate<{ author: mongoose.Document & { name?: string, email?: string } }>({
        path: 'author',
        select: 'name email _id' // Select specific fields from author
      })
      .sort({ createdAt: -1 }); // Sort by newest first

    return NextResponse.json(posts, { status: 200 });
  } catch (error: any) {
    console.error('Error fetching blog posts for admin:', error);
    return NextResponse.json({ message: 'Internal Server Error', error: error.message }, { status: 500 });
  }
}